DROP TABLE themes;
DROP TABLE icons;
DROP TABLE reservation_slots;
DROP TABLE livestream_viewers_history;
DROP TABLE livecomment_reports;
DROP TABLE ng_words;
DROP TABLE reactions;
DROP TABLE tags;
DROP TABLE livestream_tags;
DROP TABLE livecomments;
DROP TABLE livestreams;
DROP TABLE users;

ALTER TABLE `themes` auto_increment = 1;
ALTER TABLE `icons` auto_increment = 1;
ALTER TABLE `reservation_slots` auto_increment = 1;
ALTER TABLE `livestream_tags` auto_increment = 1;
ALTER TABLE `livestream_viewers_history` auto_increment = 1;
ALTER TABLE `livecomment_reports` auto_increment = 1;
ALTER TABLE `ng_words` auto_increment = 1;
ALTER TABLE `reactions` auto_increment = 1;
ALTER TABLE `tags` auto_increment = 1;
ALTER TABLE `livecomments` auto_increment = 1;
ALTER TABLE `livestreams` auto_increment = 1;
ALTER TABLE `users` auto_increment = 1;